services:
  account_service_database:
    image: mysql:9.5.0
    container_name: account_service_database-0
    restart: always
    ports:
      - "11000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_account_service
    volumes:
      - account_service_mysql_data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h 127.0.0.1 -uroot -p$$MYSQL_ROOT_PASSWORD --silent",
        ]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 20s

  account_service:
    image: fiagram_account_service:0.0.0
    container_name: account_service-0
    restart: always
    ports:
      - "11001:8080"
    volumes:
      - ./configs:/home:ro
    command: /account_service -c /home/test.yaml
    depends_on:
      account_service_database:
        condition: service_healthy

volumes:
  account_service_mysql_data:

networks:
  default:
    name: fiagram_network
