development:
  dialect: mysql
  datasource: root:root@tcp(localhost:3330)/db_account_service?parseTime=true
  dir: internal/dataaccess/database/migrations/mysql
  table: migrations

mysql_env:
  dialect: mysql
  datasource: ${MYSQL_USER}:${MYSQL_PASSWORD}@tcp(${MYSQL_HOST}:${MYSQL_PORT})/${DATABASE_NAME}?parseTime=true
  dir: internal/dataaccess/database/migrations/mysql
  table: migrations
