database:
  type: mysql
  host: 0.0.0.0
  port: 11000
  username: root
  password: root
  database: db_account_service
grpc:
  address: 0.0.0.0
  port: 11001
auth:
  hash:
    cost: 10
log:
  level: debug
