database:
  type: mysql
  host: 0.0.0.0
  port: 3330
  username: root
  password: root
  database: db_account_service
grpc:
  address: 0.0.0.0
  port: 8080
auth:
  hash:
    cost: 10
log:
  level: debug
